# Author
author:
  name: Sean Callan
  url: seancallan.com
  email: sean@seancallan.com
  twitter: doomspork
  github: doomspork

# Setup
title: Elixir School
description:
  en: Lessons about the Elixir programming language
  jp: プログラミング言語Elixirのレッスン
  cn: Elixir 编程语言教程
  es: Lecciones acerca del lenguaje de programación Elixir
  pt: Lições sobre a linguagem de programação Elixir
  vi: Giáo trình cho ngôn ngữ lập trình Elixir
  ru: Уроки программирования на языке Elixir
  sk: Lekcie o programovacom jazyku Elixir
  fr: Leçons sur le langage de programmation Elixir
  gr: Μαθήματα προγραμματισμού της γλώσσας Elixir
  it: Lezioni sul linguaggio di programmazione Elixir
  my: Pelajaran mengenai bahasa aturcara Elixir
  pl: Lekcje programowania w języku Elixir
  id: Pelajaran mengenai bahasa pemrograman Elixir
  no: Leksjoner i programmeringsspråket Elixir
  ko: 프로그래밍 언어 Elixir 배우기
  uk: Навчальні матеріали про мову програмування Elixir
  tr: Elixir programlama dili dersleri
  bg: Уроци за езика за програмиране Elixir
  de: Übungen zur Programmiersprache Elixir
  bn: এলিক্সির স্কুল
baseurl: /
url: https://elixirschool.com
og_image: https://elixirschool.com/assets/fb_share.jpg
permalink: pretty
languages: ['en', 'jp', 'cn', 'es', 'pt', 'vi', 'ru', 'sk', 'fr', 'gr', 'it', 'pl', 'my', 'no', 'ko', 'id', 'uk', 'tr', 'bg', 'de', 'bn']
rtl_languages: ['ar']
default_lang: en
exclude_from_localization: []
sections:
  - tag: basics
    label:
      en: Basics
      jp: 基礎
      cn: 基础
      es: Básico
      pt: Básico
      vi: Cơ bản
      ru: Основы
      my: Asas
      sk: Základy
      fr: Bases
      gr: Βασικά
      it: Base
      pl: Podstawy
      id: Dasar
      no: Grunnleggende
      ko: 기초
      uk: Основи
      tr: Temeller
      bg: Основи
      de: Grundlagen
      bn: ব্যাসিকস
  - tag: advanced
    label:
      en: Advanced
      jp: 上級
      cn: 高级
      es: Avanzado
      pt: Avançado
      vi: Nâng cao
      ru: Продвинутый
      my: Lanjutan
      sk: Pokročilé
      fr: Avancé
      gr: Προχωρημένα
      it: Avanzato
      pl: Zaawansowane
      id: Lanjutan
      no: Avansert
      ko: 심화
      uk: Просунуті
      tr: Gelişmiş
      bg: За Напреднали
      de: Erweitert
      bn: দক্ষ পর্যায়
  - tag: specifics
    label:
      en: Specifics
      jp: 詳細
      cn: 专题
      es: Específico
      pt: Específico
      vi: Cụ thể
      ru: Специфика
      my: Khusus
      sk: Špecifiká
      fr: Spécificités
      gr: Ιδιαιτερότητες
      it: Specifiche
      pl: Specyficzne
      id: Khusus
      no: Detaljer
      ko: 활용
      uk: Конкретика
      tr: Spesifik
      bg: Спесифики
      de: Einzelheiten
      bn: নিয়মাবলি
  - tag: libraries
    label:
      vi: Thư viện
      en: Libraries
      pt: Bibliotecas
      jp: ライブラリー
      ru: Библиотеки
      uk: Бібліотеки
      gr: Βιβλιοθήκες
      it: Librerie
      ko: 라이브러리
      pl: Biblioteki
      bn: লাইব্রেরিস
      cn: 程序库
gems:
  - kramdown
  - jekyll-assets
  - jekyll-sitemap

# Markdown Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
assets:
  compress:
    css: sass
    js:  uglifier

sitemap:
  file: '/sitemap.xml'
  include_posts:
      - '/index.html'
  change_frequency_name: 'change_frequency'
  priority_name: 'priority'

elixir:
  version: 1.4.0

erlang:
  OTP: 19
  erts: 8.0.2

toc:
  en: Table of Contents
  jp: 目次
  cn: 目录
  es: Tabla de contenidos
  pt: Sumário
  vi: Mục lục
  ru: Содержание
  sk: Obsah
  fr: Table des matières
  gr: Πίνακας περιεχομένων
  it: Tavola dei Contenuti
  my: Isi Kandungan
  pl: Spis treści
  no: Innholdsfortegnelse
  ko: 목차
  id: Daftar Isi
  uk: Зміст
  tr: İçerik
  bg: Съдържание
  de: Inhaltsverzeichnis
  bn: সূচীপত্র
share:
  en: Share This Page
  ru: Поделиться
  ko: 이 페이지 공유하기
  jp: このページをシェアする
  no: Del denne siden
  cn: 分享本页面
  sk: Zdieľaj túto stránku
  fr: Partager cette page
  pl: Podziel się
  id: Bagikan Halaman Ini
  uk: Поділитися
  tr: Paylaş
  bg: Споделете тази страница
  pt: Compartilhe essa página
  bn: পৃষ্ঠা শেয়ার করুন
  vi: Chia sẻ trang này

version_messages:
  en:
    outdated: "Some contents of this translation may be outdated."
    major: "Several major changes were applied to the original lesson since the last update."
    minor: "Several minor changes were applied to the original lesson since the last update."
    patch: "Several patches were applied to the original lesson since the last update."
    none: "This translation is up to date."
  gr:
    outdated: "Ίσως υπάρχει περιεχόμενο σε αυτή τη μετάφραση που δεν είναι ενημερωμένο."
    major: "Υπάρχουν αρκετές μεγάλες αλλαγές στο αρχικό μάθημα μετά την τελευταία ενημέρωση."
    minor: "Υπάρχουν αρκετές μικρές αλλαγές στο αρχικό μάθημα μετά την τελευταία ενημέρωση."
    patch: "Υπάρχουν αρκετές διορθωτικές αλλαγές στο αρχικό μάθημα μετά την τελευταία ενημέρωση."
    none: "Αυτή η μετάφραση είναι πλήρως ενημερωμένη."
  ru:
    outdated: "Некоторое содержимое этого урока может оказаться устаревшим."
    major: "С момента последнего обновления перевода в оригинальный урок были внесены серьёзные изменения."
    minor: "С момента последнего обновления перевода в оригинальный урок были внесены небольшие изменения."
    patch: "С момента последнего обновления перевода в оригинальный урок были внесены небольшие правки."
    none: "Это перевод актуальной версии оригинального урока."
  de:
    outdated: "Teile dieser Übersetzung könnten veraltet sein."
    major: "Einige größere Änderungen wurden der originalen Lektion seit der letzten Aktualisierung hinzugefügt."
    minor: "Einige kleinere Änderungen wurden der originalen Lektion seit der letzten Aktualisierung hinzugefügt."
    patch: "Einige Patches wurden der originalen Lektion seit der letzten Aktualisierung hinzugefügt."
    none: "Diese Übersetzung ist aktuell."