# Author
author:
  name: Sean Callan
  url: seancallan.com
  email: sean@seancallan.com
  twitter: doomspork
  github: doomspork

# Setup
title: Elixir School
description: Lessons about the Elixir programming language
baseurl: /
url: https://elixirschool.com
permalink: pretty
languages: ['en', 'jp', 'cn', 'es', 'pt', 'vi']
default_lang: en
exclude_from_localization: []
sections:
  - tag: basics
    label:
      en: Basics
      jp: 基礎
      cn: 基础
      es: Básico
      pt: Básico
      vi: Cơ bản
  - tag: advanced
    label:
      en: Advanced
      jp: 上級
      cn: 高级
      es: Avanzado
      pt: Avançado
      vi: Nâng cao
  - tag: specifics
    label:
      en: Specifics
      jp: 詳細
      cn: 详情
      es: Específico
      pt: Específico
      vi: Cụ thể

gems:
  - kramdown
  - jekyll-assets

# Markdown Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
assets:
  compress:
    css:  sass
    js:   uglifier
