# Author
author:
  name: Sean Callan
  url: seancallan.com
  email: sean@seancallan.com
  twitter: doomspork
  github: doomspork

# Setup
title: Elixir School
description:
  en: Lessons about the Elixir programming language
  jp: プログラミング言語Elixirのレッスン
  cn: Elixir 编程语言教程
  es: Lecciones acerca del lenguaje de programación Elixir
  pt: Lições sobre a linguagem de programação Elixir
  vi: Giáo trình cho ngôn ngữ lập trình Elixir
  ru: Уроки программирования на языке Elixir
  sk: Lekcie o programovacom jazyku Elixir
  fr: Leçons sur le langage de programmation Elixir
  gr: Μαθήματα προγραμματισμού της γλώσσας Elixir
  it: Lezioni sul linguaggio di programmazione Elixir
  my: Pelajaran mengenai bahasa aturcara Elixir
  pl: Lekcje programowania w języku Elixir
  id: Pelajaran mengenai bahasa pemrograman Elixir
  no: Leksjoner i programmeringsspråket Elixir
  ko: 프로그래밍 언어 Elixir 배우기
baseurl: /
url: https://elixirschool.com
og_image: https://elixirschool.com/assets/fb_share.jpg
permalink: pretty
languages: ['en', 'jp', 'cn', 'es', 'pt', 'vi', 'ru', 'sk', 'fr', 'gr', 'it', 'pl', 'my', 'no', 'ko', 'id']
default_lang: en
exclude_from_localization: []
sections:
  - tag: basics
    label:
      en: Basics
      jp: 基礎
      cn: 基础
      es: Básico
      pt: Básico
      vi: Cơ bản
      ru: Основы
      my: Asas
      sk: Základy
      fr: Bases
      gr: Βασικά
      it: Base
      pl: Podstawy
      id: Dasar
      no: Grunnleggende
      ko: 기초
  - tag: advanced
    label:
      en: Advanced
      jp: 上級
      cn: 高级
      es: Avanzado
      pt: Avançado
      vi: Nâng cao
      ru: Продвинутый
      my: Lanjutan
      sk: Pokročilé
      fr: Avancé
      gr: Προχωρημένα
      it: Avanzato
      pl: Zaawansowane
      id: Lanjutan
      no: Avansert
      ko: 심화
  - tag: specifics
    label:
      en: Specifics
      jp: 詳細
      cn: 详情
      es: Específico
      pt: Específico
      vi: Cụ thể
      ru: Специфика
      my: Khusus
      sk: Špecifiká
      fr: Spécificités
      gr: Ιδιαιτερότητες
      it: Specifiche
      pl: Specyficzne
      id: Khusus
      no: Detaljer
      ko: 활용

gems:
  - kramdown
  - jekyll-assets
  - jekyll-sitemap

# Markdown Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
assets:
  compress:
    css: sass
    js:  uglifier

sitemap:
  file: '/sitemap.xml'
  include_posts:
      - '/index.html'
  change_frequency_name: 'change_frequency'
  priority_name: 'priority'

elixir:
  version: 1.2.3

erlang:
  OTP: 18
  erts: 7.3

toc:
  en: Table of Contents
  jp: 目次
  cn: 目录
  es: Tabla de contenidos
  pt: Sumário
  vi: Mục lục
  ru: Содержание
  sk: Obsah
  fr: Table des matières
  gr: Πίνακας περιεχομένων
  it: Tavola dei Contenuti
  my: Isi Kandungan
  pl: Spis treści
  no: Innholdsfortegnelse
  ko: 목차
  id: Daftar Isi
