# Author
author:
  name: Sean Callan
  url: seancallan.com
  email: sean@seancallan.com
  twitter: doomspork
  github: doomspork

# Setup
title: Elixir School
description:
  en: Lessons about the Elixir programming language
  jp: プログラミング言語Elixirのレッスン
  cn: Lessons about the Elixir programming language
  es: Lecciones acerca del lenguaje de programación Elixir
  pt: Lições sobre a linguagem de programação Elixir
  vi: Giáo trình cho ngôn ngữ lập trình Elixir
  ru: Уроки программирования на языке Elixir
  sk: Lekcie o programovacom jazyku Elixir
url: https://elixirschool.com
permalink: pretty
languages: ['en', 'jp', 'cn', 'es', 'pt', 'vi', 'ru', 'sk']
default_lang: en
exclude_from_localization: []
sections:
  - tag: basics
    label:
      en: Basics
      jp: 基礎
      cn: 基础
      es: Básico
      pt: Básico
      vi: Cơ bản
      ru: Основы
      sk: Základy
  - tag: advanced
    label:
      en: Advanced
      jp: 上級
      cn: 高级
      es: Avanzado
      pt: Avançado
      vi: Nâng cao
      ru: Продвинутый
      sk: Pokročilé
  - tag: specifics
    label:
      en: Specifics
      jp: 詳細
      cn: 详情
      es: Específico
      pt: Específico
      vi: Cụ thể
      ru: Специфика
      sk: Špecifiká

gems:
  - kramdown
  - jekyll-assets
  - jekyll-sitemap

# Markdown Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
assets:
  compress:
    css: sass
    js:  uglifier

sitemap:
  file: '/sitemap.xml'
  include_posts:
      - '/index.html'
  change_frequency_name: 'change_frequency'
  priority_name: 'priority'
