# Author
author:
  name: Sean Callan
  url: seancallan.com
  email: sean@seancallan.com
  twitter: doomspork
  github: doomspork

# Setup
title: Elixir School
description:
  en: Lessons about the Elixir programming language
  jp: Lessons about the Elixir programming language
  cn: Lessons about the Elixir programming language
  es: Lessons about the Elixir programming language
  pt: Lições sobre a linguagem de programação Elixir
  vi: Lessons about the Elixir programming language
  ru: Lessons about the Elixir programming language
  my: Pelajaran mengenai bahasa aturcara Elixir
baseurl: /
url: http://localhost:4000
permalink: pretty
languages: ['en', 'jp', 'cn', 'es', 'pt', 'vi', 'ru', 'my']
default_lang: en
exclude_from_localization: []
sections:
  - tag: basics
    label:
      en: Basics
      jp: 基礎
      cn: 基础
      es: Básico
      pt: Básico
      vi: Cơ bản
      ru: Основы
      my: Asas
  - tag: advanced
    label:
      en: Advanced
      jp: 上級
      cn: 高级
      es: Avanzado
      pt: Avançado
      vi: Nâng cao
      ru: Продвинутый
      my: Lanjutan
  - tag: specifics
    label:
      en: Specifics
      jp: 詳細
      cn: 详情
      es: Específico
      pt: Específico
      vi: Cụ thể
      ru: Специфика
      my: Khusus

gems:
  - kramdown
  - jekyll-assets

# Markdown Config
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Assets
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
assets:
  compress:
    css:  sass
    js:   uglifier
