---
name: School House Deploy

on:
  push:
    branches:
      - content-only-changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST \
          -H "Authorization: Bearer ${{secrets.PAT_TOKEN}}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/elixirschool/school_house/actions/workflows/deploy.yml/dispatches \
          -d '{"ref": "master"}'
